# -*- coding: utf-8 -*-
"""Instagram Data Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1roetphoo9pDg-3Ucg-WPiqLtQFWcTy7W

# Instagram Data Analysis

## 1 Read File from G sheet

df is the main dataframe, 5 rows × 22 columns, N=107


> ['Post ID', 'Account ID', 'Account username', 'Account name', 'Description', 'Description (English)', '分類編碼', 'Duration (sec)', 'Publish time', 'Permalink', 'Post type', 'Data comment', 'Date', 'Total_interactions', 'Avg_eng', 'Views', 'Reach', 'Likes', 'Shares', 'Follows', 'Comments', 'Saves']
"""

import pandas as pd

# Step 1: Install gspread (optional, usually preinstalled in Colab)
!pip install --quiet gspread

# Step 2: Import Google authentication
from google.colab import auth
auth.authenticate_user()

# Step 3: Connect to Google Drive
from google.auth import default
import gspread
creds, _ = default()
gc = gspread.authorize(creds)

# Step 4: Open your sheet (replace with the actual sheet name)
sheet = gc.open("data").sheet1   # or gc.open_by_url("https://docs.google.com/spreadsheets/d/xxxxxx/edit")

# Step 5: Convert to DataFrame #the main dataframe call df
df = pd.DataFrame(sheet.get_all_records())
df.head()

#get the col names
print(df.columns.tolist())

"""## 2 Clean data

here we get the df_clean



> ['Description', 'Des_eng', 'Label', 'Duration (sec)', 'Publish time', 'Permalink', 'Post type', 'Date', 'Total_interactions', 'Avg_eng', 'Views', 'Reach', 'Likes', 'Shares', 'Follows', 'Comments', 'Saves']




"""

# Rename
df.rename(columns={'分類編碼': 'Label',
                   'Description (English)': 'Des_eng',
                   'Avg_eng' :'Engagement_Rate'}, inplace=True)
df.columns

# select only few col
df = df[df['Post type'] != 'IG image']

df_clean = df.drop(columns=['Post ID', 'Account ID', 'Account username', 'Account name', 'Data comment'], errors='ignore')


# get rid of IG image since it's only 1 post


df_clean.head()

#get the col names
print(df_clean.columns.tolist())

"""## 3 Explore the data (total_interaction)"""

# how many different type of post?
df['Post type'].unique()

#group by post type
#grouped_post_type = df.groupby('Post type')

#計算短影片和貼文的總互動數
summary = df.groupby('Post type')['Total_interactions'].agg(['count','mean','std','median','min','max']).reset_index()
print(summary)

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
sns.histplot(data=df,
             x='Total_interactions',
             hue='Post type',
             kde=True,
             bins=30,
             alpha=0.6)

plt.title('Distribution of Total Interactions (Before Removing Outliers)')
plt.xlabel('Total Interactions')
plt.ylabel('Count')
plt.show()

# print out the table without removing outliers, currently, n=106
!pip install reportlab

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
import pandas as pd

# example summary
summary = pd.DataFrame({
    'Post type': ['IG carousel', 'IG reel'],
    'N': [27, 79],
    'Mean': [859.44, 980.22],
    'SD': [2146.25, 3849.87],
    'Median': [158.0, 100.0],
    'Min': [35, 23],
    'Max': [10870, 29165]
})

# convert to list for reportlab table
data = [summary.columns.tolist()] + summary.values.tolist()

# create PDF
pdf_path = "/content/drive/MyDrive/data/APA_Table.pdf"
doc = SimpleDocTemplate(pdf_path, pagesize=letter)
styles = getSampleStyleSheet()
elements = []

# caption
caption = Paragraph("Table 1\nDescriptive Statistics by Post Type", styles["Normal"])
elements.append(caption)
elements.append(Spacer(1, 12))

# table
table = Table(data, hAlign='CENTER')
table.setStyle(TableStyle([
    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
    ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
    ('LINEBELOW', (0, 0), (-1, 0), 1, colors.black),
    ('LINEABOVE', (0, -1), (-1, -1), 1, colors.black),
    ('BOTTOMPADDING', (0, 0), (-1, 0), 6),
    ('TOPPADDING', (0, 0), (-1, 0), 6),
    ('FONTSIZE', (0, 0), (-1, -1), 10),
]))

elements.append(table)
doc.build(elements)

print(f"✅ APA table exported successfully: {pdf_path}")

"""## 4 Remove the total interaction Outleirs  (total_interaction)"""

# Calculate IQR for each post type separately
def remove_outliers(group):
    Q1 = group['Total_interactions'].quantile(0.25)
    Q3 = group['Total_interactions'].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    return group[(group['Total_interactions'] >= lower) & (group['Total_interactions'] <= upper)]

df_no_outliers = df.groupby('Post type', group_keys=False).apply(remove_outliers)

# check how many removed
print("Before:", len(df))
print("After:", len(df_no_outliers))

# who are the outlier?

def get_outliers(group):
    Q1 = group['Total_interactions'].quantile(0.25)
    Q3 = group['Total_interactions'].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    return group[(group['Total_interactions'] < lower) | (group['Total_interactions'] > upper)]

outliers = df.groupby('Post type', group_keys=False).apply(get_outliers)

print("Number of outliers:", len(outliers))
outliers[['Post type', 'Total_interactions', 'Description (English)', 'Permalink']]

#1️⃣ Recalculate descriptive stats
#Run your groupby summary again:

summary_clean = df_no_outliers.groupby('Post type')['Total_interactions'].agg(['count','mean','std','median','min','max']).reset_index()
print(summary_clean)

#distribution visual

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
sns.histplot(data=df_no_outliers,
             x='Total_interactions',
             hue='Post type',
             kde=True,
             bins=30,
             alpha=0.6)

plt.title('Distribution of Total Interactions (After Removing Outliers)')
plt.xlabel('Total Interactions')
plt.ylabel('Count')
plt.show()

#2️⃣ Check normality (optional but useful)
#If you plan to do statistical tests:

from scipy.stats import shapiro
for t, g in df_no_outliers.groupby('Post type'):
    print(t, shapiro(g['Total_interactions']))

"""```
IG carousel ShapiroResult(statistic=np.float64(0.8244585346555124), pvalue=np.float64(0.0009694420065747539))
IG reel ShapiroResult(statistic=np.float64(0.8290558851640499), pvalue=np.float64(1.5448489791880302e-07))
```

> 🧠 Shapiro–Wilk test checks if your data are normally distributed.

Null hypothesis (H₀): the data are normal.

Alternative hypothesis (H₁): the data are not normal.

for your results:

IG carousel: p = 0.00097

IG reel: p = 0.00000015

since both p-values are < .05, you reject H₀, meaning the distributions of total interactions for both post types are not normal.

👉 In short: your engagement data are skewed, probably because a few posts performed extremely well (even after removing outliers).
so for comparing groups, you should use a non-parametric test like Mann–Whitney U test instead of a t-test.
"""

from scipy.stats import mannwhitneyu

# Split by post type
carousel = df_no_outliers[df_no_outliers['Post type'] == 'IG carousel']['Total_interactions']
reel = df_no_outliers[df_no_outliers['Post type'] == 'IG reel']['Total_interactions']

# Run Mann–Whitney U test (two-tailed)
stat, p = mannwhitneyu(carousel, reel, alternative='two-sided')

print(f"U statistic = {stat:.2f}")
print(f"p-value = {p:.4f}")

"""Interpretation:

If p < .05, there’s a significant difference in engagement between IG carousels and reels.

If p ≥ .05, no significant difference is found.
p = 0.0634 is greater than .05, so the difference in total interactions between IG carousels and IG reels is not statistically significant.

In plain terms: even though reels seem to get higher average engagement, the variation is large enough that it’s not a consistent or reliable difference across your sample.

📄 APA-style report example:

A Mann–Whitney U test indicated that total interactions did not significantly differ between IG carousels (Mdn = 158) and IG reels (Mdn = 100), U = 1014.00, p = .063.



> since p = 0.063 is above .05, it means there’s no statistically significant difference — so, yeah, carousel and reel posts perform roughly the same in your sample.

> but just a nuance 👇

> it doesn’t mean they’re identical, just that the difference isn’t strong or consistent enough to rule out random chance.

> you can cautiously say: “Post type does not appear to significantly influence engagement.”

> still, if you see patterns (like reels having higher mean but big variability), that could suggest some practical difference, even if not statistically significant yet.


"""

# see the effect size, how meaningful it is for this test, unable to prove H0 wrong, to be trully meaningful?
from scipy.stats import mannwhitneyu, norm
import numpy as np

# split groups again
carousel = df_no_outliers[df_no_outliers['Post type'] == 'IG carousel']['Total_interactions']
reel = df_no_outliers[df_no_outliers['Post type'] == 'IG reel']['Total_interactions']

# Mann–Whitney U test
U, p = mannwhitneyu(carousel, reel, alternative='two-sided')

# calculate Z and r
n1, n2 = len(carousel), len(reel)
mean_U = n1 * n2 / 2
std_U = np.sqrt(n1 * n2 * (n1 + n2 + 1) / 12)
z = (U - mean_U) / std_U
r = z / np.sqrt(n1 + n2)

print(f"U = {U:.2f}, p = {p:.4f}, z = {z:.3f}, r = {r:.3f}")

"""r = 0.193 → this is a small effect size (since 0.1 = small, 0.3 = medium).

p = .063 → not statistically significant, but it’s close to .05 — we’d call this a trend-level difference.

🧠 Interpretation:
There’s a slight tendency for IG reels to get higher engagement than carousels, but the difference is small and not statistically reliable.
So you can say:

Although IG reels showed somewhat higher total interactions on average, the difference compared to carousels was small (r = .19) and did not reach statistical significance (U = 1014.00, p = .063).

basically: the post type has a minor effect, but it’s not strong enough to claim a real difference in engagement.

## 5 Engagement rate
"""

df_clean.head()

# how many different type of post?
df['Post type'].unique()

#group by post type
#grouped_post_type = df.groupby('Post type')

#計算短影片和貼文的總互動數
summary = df.groupby('Post type')['Engagement_Rate'].agg(['count','mean','std','median','min','max']).reset_index()
print(summary)

# see the ditribution
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
sns.histplot(data=df,
             x='Engagement_Rate',
             hue='Post type',
             kde=True,
             bins=30,
             alpha=0.6)

plt.title('Distribution of Engagement_Rate (Before Removing Outliers)')
plt.xlabel('Engagement_Rate')
plt.ylabel('Count')
plt.show()

#remove outliers

# Calculate IQR for each post type separately
def remove_outliers(group):
    Q1 = group['Engagement_Rate'].quantile(0.25)
    Q3 = group['Engagement_Rate'].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    return group[(group['Engagement_Rate'] >= lower) & (group['Engagement_Rate'] <= upper)]

df_no_outliers = df.groupby('Post type', group_keys=False).apply(remove_outliers)

# check how many removed
print("Before:", len(df))
print("After:", len(df_no_outliers))

# who are the outlier?

def get_outliers(group):
    Q1 = group['Engagement_Rate'].quantile(0.25)
    Q3 = group['Engagement_Rate'].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    return group[(group['Engagement_Rate'] < lower) | (group['Engagement_Rate'] > upper)]

outliers = df.groupby('Post type', group_keys=False).apply(get_outliers)

print("Number of outliers:", len(outliers))
outliers[['Post type', 'Engagement_Rate', 'Des_eng', 'Permalink']]

#1️⃣ Recalculate descriptive stats
#Run your groupby summary again:

summary_clean = df_no_outliers.groupby('Post type')['Engagement_Rate'].agg(['count','mean','std','median','min','max']).reset_index()
print(summary_clean)

#distribution visual

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
sns.histplot(data=df_no_outliers,
             x='Engagement_Rate',
             hue='Post type',
             kde=True,
             bins=30,
             alpha=0.6)

plt.title('Distribution of Engagement_Rate (After Removing Outliers)')
plt.xlabel('Engagement_Rate')
plt.ylabel('Count')
plt.show()

#2️⃣ Check normality (optional but useful)
#If you plan to do statistical tests:

from scipy.stats import shapiro
for t, g in df_no_outliers.groupby('Post type'):
    print(t, shapiro(g['Engagement_Rate']))

"""IG carousel: p = 0.059 → this is slightly above .05, so you fail to reject H₀ → ✅ engagement rates for carousels can be considered approximately normal.

IG reel: p = 0.0057 → this is below .05, so you reject H₀ → ❌ reels’ engagement rates are not normally distributed.

🧠 Summary:

Carousel → roughly normal

Reel → not normal

So overall, your data violate normality (since at least one group isn’t normal).
→ That means you should still use a non-parametric test (Mann–Whitney U) to compare engagement rates between post types.
"""

from scipy.stats import mannwhitneyu

# Split by post type
carousel = df_no_outliers[df_no_outliers['Post type'] == 'IG carousel']['Engagement_Rate']
reel = df_no_outliers[df_no_outliers['Post type'] == 'IG reel']['Engagement_Rate']

# Run Mann–Whitney U test (two-tailed)
stat, p = mannwhitneyu(carousel, reel, alternative='two-sided')

print(f"U statistic = {stat:.2f}")
print(f"p-value = {p:.4f}")

"""nice 👍 here’s the breakdown:

p = 0.3796 → way above .05 → you fail to reject H₀.

that means there’s no significant difference in engagement rate between IG carousels and IG reels.

U = 920.50 is the test statistic, but since p is large, it’s not meaningful here.

🧠 Interpretation:
Even after accounting for outliers and non-normality, post type (carousel vs. reel) does not significantly affect engagement rate.
You can phrase it in APA style like:

A Mann–Whitney U test showed no significant difference in engagement rate between IG carousels (Mdn = …) and IG reels (Mdn = …), U = 920.50, p = .38.

basically — post type doesn’t seem to matter much for engagement rate either.
"""



"""## 6 一個功能把結果直接跑完"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import shapiro, mannwhitneyu
import numpy as np

def analyze_group_diff(df, group_col, value_col):
    print(f"\n📊 Analyzing: {value_col} grouped by {group_col}\n")

    # --- 1️⃣ Remove outliers using IQR within each group ---
    def remove_outliers(g):
        Q1, Q3 = g[value_col].quantile([0.25, 0.75])
        IQR = Q3 - Q1
        lower, upper = Q1 - 1.5 * IQR, Q3 + 1.5 * IQR
        return g[(g[value_col] >= lower) & (g[value_col] <= upper)]

    df_no_outliers = df.groupby(group_col, group_keys=False).apply(remove_outliers)
    print(f"Original n = {len(df)}, after removing outliers = {len(df_no_outliers)}")

    # --- 2️⃣ Identify outliers ---
    def get_outliers(g):
        Q1, Q3 = g[value_col].quantile([0.25, 0.75])
        IQR = Q3 - Q1
        lower, upper = Q1 - 1.5 * IQR, Q3 + 1.5 * IQR
        return g[(g[value_col] < lower) | (g[value_col] > upper)]

    outliers = df.groupby(group_col, group_keys=False).apply(get_outliers)
    print("\n🚨 Outliers detected:")
    if len(outliers) == 0:
        print("No outliers found.")
    else:
        display(outliers[[group_col, value_col]])

    # --- 3️⃣ Distribution visualization ---
    plt.figure(figsize=(8,5))
    sns.histplot(data=df_no_outliers, x=value_col, hue=group_col, kde=True, bins=30, alpha=0.6)
    plt.title(f'Distribution of {value_col} by {group_col} (After Removing Outliers)')
    plt.xlabel(value_col)
    plt.ylabel('Count')
    plt.show()

    # --- 4️⃣ Normality check (Shapiro-Wilk) ---
    print("\n🧪 Shapiro–Wilk Normality Test:")
    for name, g in df_no_outliers.groupby(group_col):
        stat, p = shapiro(g[value_col])
        print(f"{name}: W = {stat:.3f}, p = {p:.4f}")

    # --- 5️⃣ Mann–Whitney U Test + Effect Size ---
    groups = list(df_no_outliers[group_col].unique())
    if len(groups) == 2:
        g1 = df_no_outliers[df_no_outliers[group_col] == groups[0]][value_col]
        g2 = df_no_outliers[df_no_outliers[group_col] == groups[1]][value_col]
        U, p = mannwhitneyu(g1, g2, alternative='two-sided')

        # Calculate effect size (r)
        n1, n2 = len(g1), len(g2)
        mean_U = n1 * n2 / 2
        std_U = np.sqrt(n1 * n2 * (n1 + n2 + 1) / 12)
        z = (U - mean_U) / std_U
        r = z / np.sqrt(n1 + n2)

        print(f"\n⚖️ Mann–Whitney U Test between {groups[0]} and {groups[1]}:")
        print(f"U = {U:.2f}, p = {p:.4f}, z = {z:.3f}, r = {r:.3f}")

        if p < 0.05:
            print("→ Significant difference (p < .05)")
        else:
            print("→ No significant difference (p ≥ .05)")

        # Effect size interpretation
        if abs(r) < 0.1:
            effect = "negligible"
        elif abs(r) < 0.3:
            effect = "small"
        elif abs(r) < 0.5:
            effect = "medium"
        else:
            effect = "large"
        print(f"Effect size: {r:.3f} ({effect})")
    else:
        print("\n⚖️ Mann–Whitney U Test skipped (requires exactly 2 groups).")

    return df_no_outliers

analyze_group_diff(df, "Label", "Engagement_Rate")

"""### 影片還是貼文？誰比較會有追蹤者"""

analyze_group_diff(df, "Post type", "Follows")

"""### 影片還是貼文比較會被分享？"""

analyze_group_diff(df, "Post type", "Shares")

"""### 影片還是貼文，被saves"""

analyze_group_diff(df, "Post type", "Saves")

"""### 影片還是貼文被 Comments"""

analyze_group_diff(df, "Post type", "Comments")

"""## 7 who are our audience"""

import pandas as pd
import gspread
from google.colab import auth
from google.auth import default

# 1️⃣ authenticate Google
auth.authenticate_user()
creds, _ = default()
gc = gspread.authorize(creds)

# 2️⃣ open your Google Sheet by name (title seen in Drive)
sh = gc.open("Audience")

# 3️⃣ list all worksheets
worksheets = sh.worksheets()
print("All pages:", [ws.title for ws in worksheets])

# 4️⃣ read all pages into DataFrames (UTF-8 by default)
df_dict = {}
for ws in worksheets:
    df = pd.DataFrame(ws.get_all_records())  # Google Sheets data is UTF-8 encoded automatically
    df_dict[ws.title] = df
    print(f"✅ Loaded: {ws.title} ({df.shape[0]} rows)")



# Example: access a specific page
df_age_gender = df_dict['Age gender']
df_cities = df_dict['Top cities']
df_countries = df_dict['Top countries']
df_follows = df_dict['Follows']
df_top_pages = df_dict['Top pages']
# check
df_age_gender.head()

df_cities.head()

df_countries.head()

df_follows.head()

df_top_pages.head()

"""### 7-1 Age and Gender"""

import seaborn as sns
import matplotlib.pyplot as plt

# melt the data so you have 'Gender' and 'Percent' columns
m = df_age_gender.melt(id_vars='Age & gender', value_vars=['Women', 'Men'],
                       var_name='Gender', value_name='Percent')

plt.figure(figsize=(5,5))

#change color
palette = {'Women': '#f150ad', 'Men': '#f6f4de'}

ax = sns.barplot(data=m, x='Age & gender', y='Percent', hue='Gender', palette=palette)  # <-- assign to ax
plt.title('Audience by Age & Gender')
plt.xlabel('Age group')
plt.ylabel('Percent')




# remove chart frame (top & right)
sns.despine(top=True, right=True, left=True, bottom=True)

# add labels on each bar
for container in ax.containers:
    ax.bar_label(container, fmt='%.1f', label_type='edge', fontsize=8, color='black', padding=2)



plt.show()

"""### set up to read chinese

解法來自：https://colab.research.google.com/github/willismax/matplotlib_show_chinese_in_colab/blob/master/matplotlib_show_chinese_in_colab.ipynb#scrollTo=mzmPaN_xHfQg
"""

# Colab 進行matplotlib繪圖時顯示繁體中文
# 下載台北思源黑體並命名taipei_sans_tc_beta.ttf，移至指定路徑
!wget -O TaipeiSansTCBeta-Regular.ttf https://drive.google.com/uc?id=1eGAsTN1HBpJAkeVM57_C7ccp7hbgSz3_&export=download

import matplotlib

# 改style要在改font之前
# plt.style.use('seaborn')

matplotlib.font_manager.fontManager.addfont('TaipeiSansTCBeta-Regular.ttf')
matplotlib.rc('font', family='Taipei Sans TC Beta')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""### 7-2 Top pages what are they watching? if not us?"""

df_top_pages.head()

df_top_pages.columns

import seaborn as sns
import matplotlib.pyplot as plt

# melt into long format
df_top_pages_melt = df_top_pages.melt(var_name='Page', value_name='Percent')

# sort by Percent descending
df_top_pages_melt = df_top_pages_melt.sort_values('Percent', ascending=False)



plt.figure(figsize=(5,5))
ax = sns.barplot(data=df_top_pages_melt, y='Page', x='Percent')  # you can change color here

plt.title('Top Pages Followed by Audience')
plt.xlabel('Percent (%)')
plt.ylabel('')
sns.despine(top=True, right=True)

# add labels on each bar
for container in ax.containers:
    ax.bar_label(container, fmt='%.1f', label_type='edge', fontsize=8, color='black', padding=2)


plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(5,5))
ax = sns.barplot(
    data=df_top_pages_melt,
    y='Page',
    x='Percent',
    color='#92ba92'
)

plt.title('Top Pages Followed by Audience', fontsize=12)
plt.xlabel('Percent (%)')
plt.ylabel('')
sns.despine(top=True, right=True, bottom=True, left=True)

# remove y-axis labels since we'll draw them on bars
ax.set_yticklabels([])

# draw each category name on its bar (左對齊、放在 bar 內上方)
for p, label in zip(ax.patches, df_top_pages_melt['Page']):
    ax.text(
        0.3,                                 # slight right padding from left edge
        p.get_y() + p.get_height() * 0.7,    # a bit above bar middle
        label,
        ha='left', va='center', color='white', fontsize=9, weight='bold'
    )
    # numeric label on right
    ax.text(
        p.get_width() + 0.3,
        p.get_y() + p.get_height() / 2,
        f"{p.get_width():.1f}",
        ha='left', va='center', color='black', fontsize=9
    )

plt.tight_layout()
plt.show()

"""# 8 Which topic is most popular (engagment rate)"""

df_clean.head()

import matplotlib.pyplot as plt

# mapping English labels to Chinese names
label_map = {
    'A1': '投資理財策略',
    'A2': '親子財商教育',
    'A3': '退休規劃',
    'A4': '保險規劃',
    'A5': '個人成長 & 理財觀念',
    'A6': '稅務 & 公司財務',
    'A7': '產業趨勢 & 時事評論',
    'A8': '女性理財 & 生活哲學'
}

# group by label
topic_engagement = (
    df_clean.groupby('Label')['Engagement_Rate']
    .mean()
    .sort_values(ascending=False)
    .reset_index()
)

# add Chinese names
topic_engagement['Label_Chinese'] = topic_engagement['Label'].map(label_map)

# visualize
plt.figure(figsize=(8,5))
plt.barh(topic_engagement['Label_Chinese'], topic_engagement['Engagement_Rate'])
plt.xlabel('平均互動率 (Engagement Rate)')
plt.ylabel('主題 (Topic)')
plt.title('各主題平均互動率')
plt.gca().invert_yaxis()
plt.show()

print(topic_engagement)

import matplotlib.pyplot as plt
import numpy as np

# mapping English labels to Chinese names
label_map = {
    'A1': '投資理財策略',
    'A2': '親子財商教育',
    'A3': '退休規劃',
    'A4': '保險規劃',
    'A5': '個人成長 & 理財觀念',
    'A6': '稅務 & 公司財務',
    'A7': '產業趨勢 & 時事評論',
    'A8': '女性理財 & 生活哲學'
}

# group and sort
topic_engagement = (
    df_clean.groupby('Label')['Engagement_Rate']
    .mean()
    .sort_values(ascending=False)
    .reset_index()
)

# add Chinese names
topic_engagement['Label_Chinese'] = topic_engagement['Label'].map(label_map)

# gradient color (yellow hue)
colors = plt.cm.YlOrBr(np.linspace(0.4, 1, len(topic_engagement)))

# plot
plt.figure(figsize=(8, 5))
bars = plt.barh(topic_engagement['Label_Chinese'], topic_engagement['Engagement_Rate'], color=colors)

# add labels beside bars
for bar in bars:
    plt.text(
        bar.get_width() + 0.002,  # slightly to the right of bar
        bar.get_y() + bar.get_height()/2,
        f"{bar.get_width():.2f}",  # format to 2 decimals
        va='center',
        fontsize=10
    )

plt.xlabel('平均互動率 (Engagement Rate)')
plt.ylabel('主題 (Topic)')
plt.title('各主題平均互動率')
plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# label map
label_map = {
    'A1': '投資理財策略',
    'A2': '親子財商教育',
    'A3': '退休規劃',
    'A4': '保險規劃',
    'A5': '個人成長 & 理財觀念',
    'A6': '稅務 & 公司財務',
    'A7': '產業趨勢 & 時事評論',
    'A8': '女性理財 & 生活哲學'
}

# count posts per label
label_count = df_clean['Label'].value_counts().sort_values(ascending=False)
label_count = label_count.rename_axis('Label').reset_index(name='Count')
label_count['Label_Chinese'] = label_count['Label'].map(label_map)

# gradient color (yellow hue)
colors = plt.cm.YlOrBr(np.linspace(0.4, 1, len(label_count)))

# plot
plt.figure(figsize=(8,5))
bars = plt.bar(label_count['Label_Chinese'], label_count['Count'], color=colors)

# add count on top
for bar in bars:
    plt.text(bar.get_x() + bar.get_width()/2,
             bar.get_height() + 0.2,
             f"{int(bar.get_height())}",
             ha='center', va='bottom', fontsize=10)

plt.xlabel('主題 (Topic)')
plt.ylabel('貼文數量 (Post Count)')
plt.title('各主題貼文數量')
plt.xticks(rotation=25, ha='right')
plt.tight_layout()
plt.show()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

label_map = {
    'A1': '投資理財策略','A2': '親子財商教育','A3': '退休規劃','A4': '保險規劃',
    'A5': '個人成長 & 理財觀念','A6': '稅務 & 公司財務','A7': '產業趨勢 & 時事評論','A8': '女性理財 & 生活哲學'
}

# 兼容欄位名：Engagement_Rate 或 Avg_eng
eng_col = 'Engagement_Rate' if 'Engagement_Rate' in df_clean.columns else 'Avg_eng'

summary = (
    df_clean.groupby('Label')
            .agg(Engagement_Rate=(eng_col, 'mean'),
                 Post_Count=('Label', 'count'))
            .reset_index()
            .sort_values('Engagement_Rate', ascending=False)
)
summary['Label_Chinese'] = summary['Label'].map(label_map)

fig, ax1 = plt.subplots(figsize=(9,5))

# Bar: 互動率
colors = plt.cm.YlOrBr(np.linspace(0.4, 1, len(summary)))
bars = ax1.bar(summary['Label_Chinese'], summary['Engagement_Rate'],
               color=colors, label='平均互動率 (Bar)')
for b in bars:
    ax1.text(b.get_x()+b.get_width()/2, b.get_height()+0.002,
             f"{b.get_height():.2f}", ha='center', va='bottom', fontsize=9)

ax1.set_ylabel('平均互動率', color='saddlebrown')
ax1.tick_params(axis='y', labelcolor='saddlebrown')
ax1.set_title('各主題投入與表現（Bar=互動率，Line=貼文數）')

# Line: 貼文數
ax2 = ax1.twinx()
(line,) = ax2.plot(summary['Label_Chinese'], summary['Post_Count'],
                   marker='o', linewidth=2, color='darkorange',
                   label='貼文數量 (Line)')
ax2.set_ylabel('貼文數量', color='darkorange')
ax2.tick_params(axis='y', labelcolor='darkorange')

# x 軸標籤角度（避免重疊）
for lbl in ax1.get_xticklabels():
    lbl.set_rotation(25)
    lbl.set_ha('right')

# 合併雙軸圖例
h1, l1 = ax1.get_legend_handles_labels()
h2, l2 = ax2.get_legend_handles_labels()
ax1.legend(h1+h2, l1+l2, loc='upper left', bbox_to_anchor=(0.5, 0.9), frameon=False)




plt.tight_layout()
plt.show()

"""# 9 Word Cloud

"""

import jieba
import pandas as pd

# --- stopwords (basic only, not domain-specific yet) ---
stopwords = {
    "的","了","和","是","在","就","都","而","及","與","著","或","一個","沒有",
    "我們","你們","他們","自己","這個","那個","如果","可以","因為","所以",
    "讓","去","來","會","要","把","也","很","還","更","以及","但","呢","啊",
    "理財","理財小時候","投資","投資理財","財商教育","股票","股票投資","投資股票",
    "https", "moneywings", "知道","其實","而是","很多","com", "org", "instagram",
    "IG", "firstory", "io", "ft", "適合", "小姐姐", "www", "還是", "不是", "真正",
    "podcast"
}

# --- tokenize and count words by label ---
word_counts_by_label = {}

for label in df_clean["Label"].unique():
    text = " ".join(df_clean[df_clean["Label"] == label]["Description"].astype(str))
    words = [
        w for w in jieba.cut(text)
        if w.strip() and w not in stopwords and len(w) > 1
    ]
    word_freq = pd.Series(words).value_counts().reset_index()
    word_freq.columns = ["Word", "Count"]
    word_counts_by_label[label] = word_freq

# --- example: view top 30 words for label A1 ---
print("Top 30 words for A1:")
print(word_counts_by_label["A1"].head(30))

from wordcloud import WordCloud
import matplotlib.pyplot as plt
import jieba

# --- use your custom font ---
import matplotlib
matplotlib.font_manager.fontManager.addfont('TaipeiSansTCBeta-Regular.ttf')
matplotlib.rc('font', family='Taipei Sans TC Beta')

font_path = 'TaipeiSansTCBeta-Regular.ttf'

# --- stopwords ---
stopwords = {
     "的","了","和","是","在","就","都","而","及","與","著","或","一個","沒有",
    "我們","你們","他們","自己","這個","那個","如果","可以","因為","所以",
    "讓","去","來","會","要","把","也","很","還","更","以及","但","呢","啊",
    "理財","理財小時候","投資","投資理財","財商教育","股票","股票投資","投資股票",
    "https", "moneywings", "知道","其實","而是","很多","com", "org", "instagram",
    "IG", "firstory", "io", "ft", "適合", "小姐姐", "www", "還是", "不是", "真正",
    "podcast", "無法", "必看", "它們", "詹璇", "就是", "什麼", "只要", "一定", "什麼",
     "怎麼", "只是", "真的", "SHINLI", "多少", "重點", "天下"
}

# --- function to generate word cloud for each label ---
def make_wordcloud_by_label(df, label_name):
    text = " ".join(df[df["Label"] == label_name]["Description"].astype(str))
    words = [w for w in jieba.cut(text) if w.strip() and w not in stopwords and len(w) > 1]

    wc = WordCloud(
        font_path=font_path,
        width=800, height=600,
        background_color="white",
        colormap="OrRd",
        max_words=15
    ).generate(" ".join(words))

    plt.figure(figsize=(8,6))
    plt.imshow(wc, interpolation="bilinear")
    plt.axis("off")
    plt.title(f"Label {label_name} - Word Cloud", fontsize=14)
    plt.show()

# --- generate for each label ---
for label in df_clean["Label"].unique():
    make_wordcloud_by_label(df_clean, label)

"""# 10 Average not raw count"""

df_clean.columns

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

# make sure names are clean
df_clean['Post type'] = df_clean['Post type'].str.strip()

# color palette (same for all charts)
palette = {'IG reel': '#FFB6B9', 'IG carousel': '#8AC6D1'}
order = ['IG reel', 'IG carousel']

# 1️⃣ Average Engagement Rate per Post Type
avg_eng = df_clean.groupby('Post type')['Engagement_Rate'].mean().reset_index()

plt.figure(figsize=(6,4))
sns.barplot(
    data=avg_eng, x='Post type', y='Engagement_Rate',
    palette=palette, order=order
)
plt.title('Average Engagement Rate by Post Type')
plt.xlabel('')
plt.ylabel('Average Engagement Rate')
plt.tight_layout()
plt.show()

# 2️⃣ Distribution (all data)
plt.figure(figsize=(6,4))
sns.boxplot(
    data=df_clean, x='Post type', y='Engagement_Rate',
    palette=palette, order=order
)
plt.title('Distribution of Engagement Rate by Post Type')
plt.xlabel('')
plt.ylabel('Engagement Rate')
plt.tight_layout()
plt.show()

# 3️⃣ Equal sample size (fair comparison)
min_n = df_clean['Post type'].value_counts().min()
df_sampled = df_clean.groupby('Post type').sample(n=min_n, random_state=42)

plt.figure(figsize=(6,4))
sns.boxplot(
    data=df_sampled, x='Post type', y='Engagement_Rate',
    palette=palette, order=order
)
plt.title('Fair Comparison (Equal Sample Size)')
plt.xlabel('')
plt.ylabel('Engagement Rate')
plt.tight_layout()
plt.show()

"""```
# This is formatted as code
```

# 1️⃣ 不同分類的平均互動率比較（橫條圖）

## Data Cleaning
"""

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
from matplotlib import font_manager

# 設定字體
plt.rcParams['font.family'] = 'sans-serif'
plt.rcParams['axes.unicode_minus'] = False

# 讀取資料
# 請將 'your_data.csv' 替換成你的實際檔案路徑
df = pd.read_csv('/content/drive/MyDrive/data/data.csv')

# keep only the part before '-'
#df['分類編碼'] = df['分類編碼'].str.split('-').str[0]

# confirm change
#print(df['分類編碼'].unique())


# 資料清理：確保數值欄位是數字格式 Like+Comment+Saves+Shares+follows
df['Likes'] = pd.to_numeric(df['Likes'], errors='coerce')
df['Comments'] = pd.to_numeric(df['Comments'], errors='coerce')
df['Saves'] = pd.to_numeric(df['Saves'], errors='coerce')
df['Reach'] = pd.to_numeric(df['Reach'], errors='coerce')

#sares + follows
df['Shares'] = pd.to_numeric(df['Shares'], errors='coerce')
df['Follows'] = pd.to_numeric(df['Follows'], errors='coerce')


# 計算互動率
df['Engagement_Rate'] = (df['Likes'] + df['Comments'] + df['Saves']+ df['Shares'] + df['Follows']) / df['Reach'] * 100

# 按分類計算平均互動率
category_engagement = df.groupby('分類編碼')['Engagement_Rate'].mean().sort_values()

# 定義分類名稱對照（英文版）
category_names = {
    'A1': 'Investment Strategy',
    'A2': 'Kids Finance Edu',
    'A3': 'Retirement Plan',
    'A4': 'Insurance',
    'A5': 'Personal Growth',
    'A6': 'Tax & Business',
    'A7': 'Industry Trends',
    'A8': 'Women Finance'
}

# 替換分類名稱
category_engagement.index = category_engagement.index.map(category_names)

"""## Visualization"""

# 建立圖表
fig, ax = plt.subplots(figsize=(8, 8))  # ✅ 1:1 比例，適合 IG 貼文
ax.set_aspect('auto')  # 自動調整長條比例
plt.tight_layout(pad=3)  # 保留邊界空間避免被裁掉


# 繪製橫條圖


# 套用顏色到 bar
#colors = [color_map.get(cat, '#FF6B9D') for cat in category_engagement.index]

bars = ax.barh(
    category_engagement.index,
    category_engagement.values,
    color=colors,
    #edgecolor='#C7254E',
    linewidth=1.5
)


# 在每個 bar 上顯示「乾淨版」分類名稱
for i, bar in enumerate(bars):
    cat = category_engagement.index[i]
    label = clean_category_names.get(cat, cat)
    y = bar.get_y() + bar.get_height() / 2
    x = bar.get_width() * 0.02  # 讓文字稍微靠左一點
    ax.text(x, y, label, va='center', ha='left', fontsize=8, color='#333333', fontweight='bold')




# 修正：針對「水平長條圖 barh」的數值標註，避免擠在一起
xmax = float(category_engagement.max())
ax.set_xlim(0, xmax * 1.15)  # 預留右側空間給標籤
pad = xmax * 0.015           # 依資料自動調整內外距

for bar in bars:
    w = bar.get_width()
    y = bar.get_y() + bar.get_height() / 2
    # 寬的 bar 內嵌白字；窄的 bar 放外側深色字，避免重疊
    if w > xmax * 0.12:
        ax.text(w - pad, y, f'{w:.2f}%', ha='right', va='center',
                fontsize=9, fontweight='bold', color='white')
    else:
        ax.text(w + pad, y, f'{w:.2f}%', ha='left', va='center',
                fontsize=9, fontweight='bold', color='#333333')



# 設定標題和標籤
ax.set_xlabel('Average Engagement Rate (%)', fontsize=12, fontweight='bold')
ax.set_ylabel('Content Category', fontsize=8, fontweight='bold')
ax.set_title('Average Engagement Rate by Content Category\nEngagement Rate = (Likes + Comments + Saves + Shares + Follows) / Reach',
             fontsize=14, fontweight='bold', pad=20)

# 美化圖表
ax.grid(axis='x', alpha=0.3, linestyle='--')
ax.set_axisbelow(True)
plt.tight_layout()


# 顯示圖表
plt.show()

# 輸出統計資訊
print("=" * 60)
print("📊 Engagement Rate Statistics by Category")
print("=" * 60)
for category, rate in category_engagement.items():
    print(f"{category}: {rate:.2f}%")
print("=" * 60)
print(f"\n🏆 Highest Engagement: {category_engagement.idxmax()} ({category_engagement.max():.2f}%)")
print(f"📉 Lowest Engagement: {category_engagement.idxmin()} ({category_engagement.min():.2f}%)")
print(f"📊 Average Engagement: {category_engagement.mean():.2f}%")

import matplotlib.pyplot as plt
from matplotlib.patches import Patch

# 保證順序（若你想固定 A1→A8）
order = ['A1','A2','A3','A4','A5','A6','A7','A8']
category_engagement = category_engagement.reindex([c for c in order if c in category_engagement.index]).sort_values(ascending=True)

color_map = {
    'A2': '#92ba92','A4': '#a2bf95','A8': '#b1c499','A5': '#bfc99e',
    'A3': '#cdcda5','A1': '#dad2ad','A6': '#e6d8b5','A7': '#f1ddbf'
}
full_names = {
    'A1': 'Investment Strategy','A2': 'Kids Finance Edu','A3': 'Retirement Plan','A4': 'Insurance',
    'A5': 'Personal Growth','A6': 'Tax & Business','A7': 'Industry Trends','A8': 'Women Finance'
}

# --- 建立圖表 ---
fig, ax = plt.subplots(figsize=(8, 8))
ax.set_aspect('auto')
plt.tight_layout(pad=3)

# 顏色
colors = [color_map.get(cat, '#BBBBBB') for cat in category_engagement.index]

# 水平長條圖（Y 軸=代碼 A1~A8）
bars = ax.barh(
    category_engagement.index,   # 直接用代碼做 Y-axis tick
    category_engagement.values,
    color=colors,
    linewidth=1.5
)

# 數值標註（%）
xmax = float(category_engagement.max())
ax.set_xlim(0, xmax * 1.15)
pad = xmax * 0.015
for bar in bars:
    w = bar.get_width()
    y = bar.get_y() + bar.get_height() / 2
    if w > xmax * 0.12:
        ax.text(w - pad, y, f'{w:.2f}%', ha='right', va='center',
                fontsize=9, fontweight='bold', color='white')
    else:
        ax.text(w + pad, y, f'{w:.2f}%', ha='left', va='center',
                fontsize=9, fontweight='bold', color='#333333')

# 標題與座標軸（Y 軸標籤= A1–A8）
ax.set_xlabel('Average Engagement Rate (%)', fontsize=12, fontweight='bold')
ax.set_ylabel('Category (A1–A8)', fontsize=10, fontweight='bold')
ax.set_title('Average Engagement Rate by Content Category\n'
             'Engagement Rate = (Likes + Comments + Saves + Shares + Follows) / Reach',
             fontsize=14, fontweight='bold', pad=20)
ax.grid(axis='x', alpha=0.3, linestyle='--')
ax.set_axisbelow(True)

# Legend 用「完整名稱」
legend_handles = [
    Patch(facecolor=color_map[k], label=full_names[k])
    for k in [c for c in order if c in category_engagement.index]
]
leg = ax.legend(handles=legend_handles, title='Category Legend',
                loc='lower right', bbox_to_anchor=(1.0, 0.0),
                fontsize=9, title_fontsize=10, frameon=False, ncol=1)

plt.tight_layout()
plt.show()

# 輸出統計資訊
print("=" * 60)
print("📊 Engagement Rate Statistics by Category")
print("=" * 60)
for category, rate in category_engagement.items():
    print(f"{category}: {rate:.2f}%")
print("=" * 60)
print(f"\n🏆 Highest Engagement: {category_engagement.idxmax()} ({category_engagement.max():.2f}%)")
print(f"📉 Lowest Engagement: {category_engagement.idxmin()} ({category_engagement.min():.2f}%)")
print(f"📊 Average Engagement: {category_engagement.mean():.2f}%")



import matplotlib.pyplot as plt

# === Inputs assumed ===
# category_engagement: pd.Series with index like ['A1','A2',...] and values as percentages
# category_names: dict mapping code -> 'A1-Investment Strategy' (optional; used for pretty labels)

# New color logic (code -> hex)
color_map = {
    'A2': '#92ba92',
    'A4': '#a2bf95',
    'A8': '#b1c499',
    'A5': '#bfc99e',
    'A3': '#cdcda5',
    'A1': '#dad2ad',
    'A6': '#e6d8b5',
    'A7': '#f1ddbf'
}

# Sort (small -> big) for horizontal bars
category_engagement = category_engagement.sort_values(ascending=True)

# Colors for each bar (fallback to a neutral tone if missing)
colors = [color_map.get(cat, '#CCCCCC') for cat in category_engagement.index]

# Build figure
fig, ax = plt.subplots(figsize=(8, 8))  # square-ish for IG
ax.set_aspect('auto')
plt.tight_layout(pad=3)

# Plot
bars = ax.barh(
    category_engagement.index,
    category_engagement.values,
    color=colors,
    linewidth=1.5
)

# Pretty names without code prefix (safe even if category_names not provided)
if 'category_names' in globals() and isinstance(category_names, dict):
    clean_category_names = {k: (v.split('-', 1)[1] if '-' in v else v) for k, v in category_names.items()}
else:
    clean_category_names = {code: code for code in category_engagement.index}  # fallback

# Text labels on bars (left-side category name)
for i, bar in enumerate(bars):
    cat = category_engagement.index[i]
    label = clean_category_names.get(cat, cat)
    y = bar.get_y() + bar.get_height() / 2
    x = bar.get_width() * 0.02
    ax.text(x, y, label, va='center', ha='left', fontsize=8, color='#333333', fontweight='bold')

# Value labels (inside if wide, outside if narrow)
xmax = float(category_engagement.max())
ax.set_xlim(0, xmax * 1.15)  # room on the right
pad = xmax * 0.015

for bar in bars:
    w = bar.get_width()
    y = bar.get_y() + bar.get_height() / 2
    if w > xmax * 0.12:
        ax.text(w - pad, y, f'{w:.2f}%', ha='right', va='center',
                fontsize=9, fontweight='bold', color='white')
    else:
        ax.text(w + pad, y, f'{w:.2f}%', ha='left', va='center',
                fontsize=9, fontweight='bold', color='#333333')

# Titles & axes
ax.set_xlabel('Average Engagement Rate (%)', fontsize=12, fontweight='bold')
ax.set_ylabel('Content Category', fontsize=8, fontweight='bold')
ax.set_title('Average Engagement Rate by Content Category\n'
             'Engagement Rate = (Likes + Comments + Saves + Shares + Follows) / Reach',
             fontsize=14, fontweight='bold', pad=20)

# Style
ax.grid(axis='x', alpha=0.3, linestyle='--')
ax.set_axisbelow(True)
plt.tight_layout()
plt.show()